### ISSUE TITLE
Update environment

### ISSUE THREAD

**Issue by d2hydro** [hdsr-mid/hdsr_fewspy#16]
- [x] Update the Python-environment with rasterstats and rasterio to allow sampling geometries on rasters.
- [x] Consider updating to a later / the latest version of Python (now 3.7)

**Comment by d2hydro** [comment]
@renierkramerhdsr, can you check if this environment works for you: https://github.com/hdsr-mid/hdsr_fewspy/blob/update_environment/environment.yml?

**Comment by d2hydro** [comment]
@renierkramerhdsr, we need xarray and rioxarray as well.

**Comment by renierkramerhdsr** [comment]
> @renierkramerhdsr, we need xarray and rioxarray as well.

[-] the less dependencies, the better. Can the job be done without xarray and rioxarray? If so, how difficult is it? How much extra geopandas code would be required?
[+] I just created a new env including both and it works
[+] I see that both are well maintained, so i think we're safe for the next couple of years
---+
It's your call if we should go for it :)

**Comment by renierkramerhdsr** [comment]
> @renierkramerhdsr, pls check:
> 
> * if this environment works for you: https://github.com/hdsr-mid/hdsr_fewspy/blob/update_environment/environment.yml
> * if you would like to go for python > 3.7 (currently fixed at 3.7)

the yml works. 
We can bump python to 3.11 (or less)
