### ISSUE TITLE
Improve WIWB-api

### ISSUE THREAD

**Issue by d2hydro** [hdsr-mid/hdsr_fewspy#21]
- [x] renier: merge bump_python into wiwb_api
- [x] @d2hydro: update from main
- [x] pull wiwb_api changes
- [x] resolve all pyflakes errors in pytests
- [x] project geoseries to GetGrids.crs, see #17 
- [x] fix bounds issue on WIWB by buffering bounds with grid-size
- [x] include methods/examples to read VdSat/Planet data
- [x] Include typing.Literal, support 3.8 <=  Python <= 3.11
- [X] Move GLOBALS to classes in constants.py, avoid dictionaries/strings
- [x] Add numpy docstrings at all classes/methods
- [x] Release on pypi
- [x] add api.get_grids with GetGrids object as return
- [ ] release on Conda
--------------
- [ ] renier: Zorgen dat die vdsat NetCDF bestanden op een plek staan waar hdsr collega’s in VDI lees-rechten hebben.
- [ ] renier: Zorgen dat die dagelijks worden bijgevuld (windows scheduling?)
- [ ] renier: use wiwbi_api as dep in hdsr_fewspy (@d2hydro, please reserve 2 days to eventually answer my questions and/or  edit wiwb_api, etc)
- [ ] hdsr-fewspy dep wiwb gebruiken en route "lokaal vdsat bodemvocht" bouwen
- [ ] hdsr-fewspy dep wiwb gebruiken en route "wiwi neerslag" bouwen
- [ ] hdsr-fewspy dep wiwb gebruiken en route "wiwb verdamping" bouwen
--------
- [ ] optional: Use tox to run pytests across python versions

**Comment by d2hydro** [comment]
@renierkramerhdsr, ik heb de branch geupdated vanuit de main. De python dependency vindt conda niet leuk. Ik heb hem voor mezelf <= 3.12 gemaakt; dat werkt. Ik vermoed dat je de 3.7 iets hoger moet gaan zetten.

![image](https://github.com/hdsr-mid/hdsr_fewspy/assets/43996424/4a9643ed-be73-4f29-b69a-e4c96925b4c6)

**Comment by renierkramerhdsr** [comment]
@d2hydro oeps, dat is een typo. Het zou moeten zijn: ```python>3.7,<=3.12```

**Comment by d2hydro** [comment]
@renierkramerhdsr; can we specify `move all body classes to body.py` in : https://github.com/hdsr-mid/hdsr_fewspy/issues/21#issue-1994471531? I'm not 100% sure what it means, hence why I think you wrote it :-)

**Comment by d2hydro** [comment]
Verdere updates verwerkt en gelijst in de wiwb-repos onder issues:
- [x ] https://github.com/d2hydro/wiwb/issues/1
